config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets do
    resources :likes
    member do
      post :retweet
    end
  end

  post 'user/:user_id', to: 'friends#create', as: 'friend_create'
  delete 'user/:user_id', to: 'friends#destroy', as: 'friend_destroy'

  get 'api/news'
  get 'api/:fecha1/:fecha2', to: 'api#search', as: 'ask_search'

  post 'api/create', to: 'api#create_tweet'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'tweets#index'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  validates :content, presence: true
  has_many :likes, dependent: :destroy
  has_many :linking_users, :through => :likes, :source => :user
  has_many :retweets, class_name: 'Tweet', foreign_key: 'retweet_id'
  has_many :tweets
  belongs_to :tweets, optional: true

  paginates_per 50

  scope :tweets_for_me, ->(users_list) { where(
     user_id: users_list.map do |friend|
         friend.friend_id
     end
  ) }
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy retweet ]
  before_action :authenticate_user!, except: [:index]

  # GET /tweets or /tweets.json
  def index

    if params[:q]
     @tweets = Tweet.where("content LIKE ?", "%#{params[:q]}%").order(created_at: :desc).page(params[:page])
    else
       @tweets = Tweet.order(created_at: :desc).page(params[:page])
    end
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end


  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
    if @tweet.user_id != current_user.id
      redirect_to root_path, alert: 'you dont have permission for edit tweets'
    end
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def retweet
    @retweet = Tweet.new(
      user_id: current_user.id,
      content: @tweet.content,
     
    )
      if @retweet.save
        redirect_to root_path, notice: 'Retwitteado'
      else
        redirect_to root_path, alert: 'No se pudo retwittear'
      end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id, :created_at, :tweet_id)
    end

    def retweet_params
      params.require(:retweet).permit(:retweet_id, :content).merge(user_id: current_user.id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper

    def count_retweets(tweet) 
    end

    def hashtag(tweet)
        tweet.scan(/#\w+/).map{|name| name.gsub("#", "")}
    end
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this @tweet from being saved:</h2>
      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="card col-6 offset-3 d-flex">

    <div class="d-flex p-3">
      <figure class="">
        <img src="<%= current_user.profile_picture %>" style="width: 60px; height: 60px; border-radius: 50%">
      </figure>
  
      <div class="ml-auto w-75">
        <%= form.text_area(:content, placeholder: 'Escribe tu tweet...', class: 'form-control mb-2') %>
        <%= form.submit(class: 'btn btn-primary') %>
      </div>
  </div>


<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="row">
  <div class="col-md-3 offset-md-2">
    
    <% if user_signed_in? %>
      <%= link_to 'Nuevo Tweet', new_tweet_path %>
      <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Crear Cuenta', new_user_registration_path %>
      <%= link_to 'Iniciar Sesión', new_user_session_path %>
    <% end %>

  </div>
</div>





<% @tweets.each do |tweet| %>
  <div class="row d-flex justify-content-center my-3">
    <div class="col-6">
      <div class="d-flex justify-content-around">
        <div>
          <% if user_signed_in? %>
            <% pre_follow = current_user.friends.find { |friend| friend.friend_id == tweet.user.id } %>
            <% if pre_follow %>
              <%= link_to 'Dejar de seguir', friend_destroy_path(tweet.user.id), method: :delete %>
            <% else %>
              <%= link_to 'Seguir', friend_create_path(tweet.user.id), method: :post %>
            <% end %>
          <% end %>
        </div>
      </div>  

      <div class="card">
        <div class="card-body">
          <figure class="d-flex align-items-center">
            <img src="<%=tweet.user.profile_picture %>" style="width:60px; height:60px; border-radius:50%">
            <figcaption class="w-75 pl-3">
              <% tweet.content.split.each do |word| %>
                <% if word.start_with?('#') %>
                  <%= link_to word, root_path(q: word) %>
                <% else %>
                  <%= word %>
                <% end %>
              <% end %>
            </figcaption>
          </figure>
          <div class="d-flex justify-content-around">
            
            <div>
              <% if user_signed_in? %>
                <% pre_like = tweet.likes.find { |like| like.user_id == current_user.id } %>
                <% if pre_like %>
                  <%= link_to image_tag('https://www.pngfind.com/pngs/m/78-781747_leave-a-reply-cancel-reply-twitter-like-icon.png', width: 20, height: 20), tweet_like_path(tweet, pre_like), method: :delete %>
                <% else %>
                  <%= link_to image_tag('https://www.iconfinder.com/data/icons/twitter-21/512/166_Heart_Love_Like_Twitter-512.png', width: 20, height: 20), tweet_likes_path(tweet), method: :post %>
                <% end %>
                <%= tweet.likes.count %> Likes
              <% end %>
            </div>  
            <div>
              <%= link_to image_tag('https://w7.pngwing.com/pngs/497/636/png-transparent-computer-icons-scalable-graphics-apple-icon-format-twitter-retweet-icon-miscellaneous-angle-text-thumbnail.png', width:20, height: 20), retweet_tweet_path(tweet.id), method: :post %>
              <%= tweet.likes.count %> RT
            </div>
            <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id) %>
          </div>
        </div>
      </div>
    </div> 
  </div>
<%end %>





































<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= paginate @tweets %>
  </div>
</div>



  

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %> -->

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<h2>Likes</h2>
<p>
  <% @tweet.likes.each do |like| %>
  <img src="<%= like.user.profile_picture %>", style="width:40px; height:40px">
  <% end %>
</p>


<% if current_user.id == @tweet.user_id %>
  <%= link_to 'Editar', edit_tweet_path(@tweet) %> |
  <%= link_to 'Borrar', tweet_path(@tweet.id), method: :delete %> |
<% end %>

<%= link_to 'Volver', tweets_path %>